spring:
  application:
    name: smart-learning

  datasource:
    url: jdbc:mariadb://localhost:3306/smart_learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 049206
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # Flyway quản lý schema, JPA chỉ validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    execute-in-transaction: false    # cho MariaDB mới
    clean-disabled: false
    clean-on-validation-error: true

server:
  port: 8080